language: python
python:
  - "2.7"
cache: pip
install: 
  - pip install numpy
  - pip install coveralls
script: 
  - cd test
  - python -m unitTestTicTacToe
  - coverage run --source=script/TicTacToeClass.py test/unitTestTicTacToe.py
after_success:
  - coveralls
