language: python
python:
  - "2.7"
cache: pip
install: 
  - pip install numpy
  - pip install coverage
  - pip install coveralls
  
script: 
  - cd test
  - python -m unitTestTicTacToe
  - coverage run --include=../script/TicTacToeClass.py unitTestTicTacToe.py
after_success:
  - coveralls
